pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Download') {
      steps {
        sh '''
                    
                    apt install maven -y
                    echo 'mvn --version'
        '''
      }
    }
  }
}
