pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Download') {
      steps {
        apt install maven -y
        sh 'mvn --version'
  }
}
